export type SizeOption = { label: string; price: number };
export type Flavor = { id: string; name: string; image?: string };
export type Category = { id: string; name: string; eyebrow: string; description: string; sizes: SizeOption[]; flavors: Flavor[]; badge?: string };
export type SiteContent = { heroTitle: string; heroText: string; heroImage: string; categories: Category[] };

const flavors = (names: string[]): Flavor[] => names.map((name, index) => ({ id: `${name.toLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g, '').replace(/[^a-z0-9]+/g, '-')}-${index}`, name }));
const cake = ['Brigadeiro', 'Chocolate com morango', 'Ninho', 'Ninho com morango', 'Prestígio', 'Cenoura com chocolate', 'Oreo', 'Casadinho', 'Ferrero Rocher', 'Tapioca', 'Churros', 'Maracujá', 'Red velvet'];

export const defaultContent: SiteContent = {
  heroTitle: 'Seu momento mais doce começa aqui.',
  heroText: 'Escolha seus sabores, defina o tamanho e monte um pedido do seu jeitinho.',
  heroImage: '/chef-hora-do-cafe.png',
  categories: [
    { id: 'caseirinhos', name: 'Bolo caseirinho', eyebrow: 'Afeto em cada fatia', description: 'Massa macia, cobertura generosa e sabor de casa.', sizes: [{ label: '18 cm', price: 55 }, { label: '20 cm', price: 65 }, { label: '22 cm', price: 75 }], flavors: flavors(cake), badge: 'Queridinho' },
    { id: 'simples', name: 'Bolo simples', eyebrow: 'Clássicos do café', description: 'Leves, caseiros e perfeitos para qualquer hora.', sizes: [{ label: '18 cm', price: 25 }, { label: '20 cm', price: 30 }, { label: '22 cm', price: 35 }], flavors: flavors(['Formigueiro', 'Branco', 'Chocolate', 'Romeu e Julieta', 'Banana', 'Mesclado', 'Goiabada', 'Cenoura', 'Cenoura com chocolate', 'Maracujá', 'Casadinho']) },
    { id: 'vulcao', name: 'Bolo vulcão', eyebrow: 'Cobertura que transborda', description: 'Para quem acredita que recheio nunca é demais.', sizes: [{ label: '18 cm', price: 60 }, { label: '20 cm', price: 70 }, { label: '22 cm', price: 80 }], flavors: flavors([...cake.slice(0, 5), 'Limão', 'Kinder Bueno', ...cake.slice(5)]), badge: 'Bem recheado' },
    { id: 'caramelizados', name: 'Bolo caramelizado', eyebrow: 'Brilho e sabor', description: 'Frutas douradas em uma massa delicada e úmida.', sizes: [{ label: '18 cm', price: 30 }, { label: '20 cm', price: 40 }, { label: '22 cm', price: 50 }], flavors: flavors(['Abacaxi', 'Banana']) },
    { id: 'naked', name: 'Naked cake', eyebrow: 'Para celebrar bonito', description: 'Camadas aparentes, acabamento artesanal e muita presença.', sizes: [{ label: '16 cm', price: 140 }, { label: '18 cm', price: 150 }, { label: '20 cm', price: 160 }, { label: '25 cm', price: 190 }], flavors: flavors([...cake, 'Chocolate com cereal', 'Doce de leite com coco', 'Brownie', 'Bem-casado', 'Caramelo com chocolate']), badge: 'Para festas' },
    { id: 'pote', name: 'Bolo no pote', eyebrow: 'Doce na medida', description: 'Camadas cremosas em um pote individual de 250 ml.', sizes: [{ label: '250 ml', price: 19 }], flavors: flavors(['Ninho com morango', 'Brigadeiro com pedaços de chocolate', 'Brownie com chocolate', 'Brownie ninho com morango', 'Bombom de morango', 'Bombom de uva', 'Chocolate com cereal', 'Cenoura', 'Ferrero Rocher', 'Ninho']) },
    { id: 'doces-tradicionais', name: 'Doces tradicionais', eyebrow: 'Pequenas alegrias', description: 'Unidades clássicas para montar sua mesa do seu jeito.', sizes: [{ label: 'Unidade', price: 2 }], flavors: flavors(['Brigadeiro', 'Brigadeiro branco', 'Casadinho', 'Beijinho', 'Churros', 'Uva coberta', 'Cocadinha', 'Queijadinha', 'Empada doce', 'Ninho', 'Ferrero', 'Oreo', 'Quadradinho de brownie', 'Ninho com Nutella', 'Romeu e Julieta', 'Olho de sogra']) },
    { id: 'doces-finos', name: 'Doces finos', eyebrow: 'Um toque especial', description: 'Acabamento delicado para festas e momentos marcantes.', sizes: [{ label: 'Unidade', price: 2.5 }], flavors: flavors(['Morango coberto', 'Copinho de limão', 'Copinho de maracujá', 'Copinho de morango', 'Copinho dois amores', 'Nozes', 'Prestígio', 'Bis', 'Ferrero Rocher', 'Bombom de ameixa', 'Bombom de brownie', 'Bombom sequilho', 'Ninho com Nutella', 'Balinha de coco', 'Bombom de caramelo', 'Tortelete de brigadeiro', 'Tortelete casadinho', 'Tortelete doce de leite', 'Tortelete de limão']) },
    { id: 'pao-metro', name: 'Pão metro', eyebrow: 'Para compartilhar', description: 'Cinquenta centímetros de recheio, ideal para encontros.', sizes: [{ label: '50 cm', price: 90 }], flavors: flavors(['Atum', 'Misto', 'Frango', 'Queijo']) },
    { id: 'brownie', name: 'Brownie', eyebrow: 'Crocante e cremoso', description: 'Chocolate intenso em versões simples ou recheadas.', sizes: [{ label: 'Sem recheio', price: 4 }, { label: 'Recheado', price: 8 }], flavors: flavors(['Doce de leite', 'Casadinho', 'Chocolate', 'Ninho com morango', 'Ferrero', 'Ninho', 'Chocolate com morango']) },
    { id: 'tortas', name: 'Tortas', eyebrow: 'Camadas de felicidade', description: 'Feitas para serem o centro da mesa e da comemoração.', sizes: [{ label: '16 cm', price: 140 }, { label: '18 cm', price: 150 }, { label: '20 cm', price: 160 }, { label: '22 cm', price: 190 }], flavors: flavors(['Brigadeiro', 'Chocolate com morango', 'Ninho', 'Ninho com morango', 'Prestígio', 'Abacaxi', 'Kinder Bueno', 'Oreo', 'Casadinho', 'Ferrero Rocher', 'Tapioca', 'Churros', 'Maracujá', 'Doce de leite com coco', 'Chocolate com cereal', 'Bem-casado']), badge: 'Celebre' },
  ],
};
